services:
  # used to build the production image
  r:
    image: r:${MAJOR_VERSION}
    build:
      context: .
      target: r
      cache_from:  # should speed up the build in CI, where we have a cold cache
        - ghcr.io/opensafely-core/base-action:${BASE}
        - ghcr.io/opensafely-core/r:${MAJOR_VERSION}
      args:
        # this makes the image work for later cache_from: usage
        - BUILDKIT_INLINE_CACHE=1
        # env vars supplied by make/just
        - BUILD_DATE
        - CODENAME
        - CRAN_DATE
        - REPOS
        - REVISION
        - UPDATE
        - VERSION
        - BASE
        - MAJOR_VERSION
    init: true
    platform: linux/amd64
  add-package:
    extends: r
    image: "${IMAGE_TAG:-}"
    build:
      target: add-package
      args:
       - PACKAGE
    platform: linux/amd64
  rstudio:
    extends: r
    image: rstudio
    build:
      target: rstudio
      args:
        # supplied by just
        - R_LIBS_SITE
        - RSTUDIO_BASE_URL
        - RSTUDIO_DEB
    ports:
      - 8787:8787
    platform: linux/amd64
    volumes:
      - ${PWD}:/workspace
      - ${HOME}/.gitconfig:/home/rstudio/local-gitconfig
    environment:
      HOSTPLATFORM: ${HOSTPLATFORM}
      HOSTUID: ${HOSTUID}
