name: Package request
description: Request a new package be added to the r image.
title: "[Package request]: "
body:
  - type: textarea
     id: package request
     attributes:
       label: Package request
       description: Which new package/s are you requesting?
       placeholder: Please list the new package/s you require here along with their CRAN URLs. And if you know, please indicate whether the soft dependencies (Suggests list in package DESCRIPTION file) are required for the requested package/s (by default we install the hard dependencies - the Imports list in the package DESCRIPTION file).
     validations:
       required: true
