---
title: ""
output:
  github_document:
    html_preview: false
---

```{r setup, include=FALSE}
v <- Sys.getenv("MAJOR_VERSION")
r_img <- paste0("`r:", v, "`")
rstudio_img <- paste0("`rstudio:", v, "`")
local_dir <- paste0("_.local-packages/r/", v, "_")
```

# .local-packages a directory for user installed libraries

This directory contains user installed libraries, for say running OpenSAFELY code in a Codespace or locally.

## How to add and remove user installed R packages

The `r local_dir` directory contains user installed R packages to work in the `r r_img` and `r rstudio_img` images.

You can install additional packages by running

```r
install.packages("PACKAGENAME")
```

or by using the RStudio _Package_ pane _Install_ button.

Note that packages are installed from the same date from CRAN as the other packages in the `r r_img` image. This is to ensure user installed packages work with the other packages in the image (at the time of installation).

If you no longer require a package you can also remove it as follows.

```r
remove.packages("PACKAGENAME")
```

You can also install packages from Git repositories such as GitHub, install the remotes package first as follows.

```r
install.packages("remotes")
remotes::install_github("USERNAME/PACKAGENAME")
```

Please see the [r-docker repository README](https://github.com/opensafely-core/r-docker?tab=readme-ov-file#r-docker) if you require more information.
