name: Build docker image and publish
on:
  push:
    branches: [master]
env:
  IMAGE_NAME: r
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
    - name: Log into GitHub Container Registry
      run: docker login https://ghcr.io -u ${{ github.actor }} --password ${{ secrets.CR_PAT }}
    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
    - name: Write packages
      id: write_packages
      run: |
        packages=$(docker run $IMAGE_NAME -e 'write.csv(installed.packages()[, c("Package","Version")], row.names=FALSE)')
        echo "::set-output name=packages=$packages"
    - name: Publish package list
      id: packages_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: R Packages included in ${{ github.ref }}
        body: |
          R packages in this image:
          ${{ steps.write_packages.outputs.packages }}
        draft: false
        prerelease: false
    # deprecated
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: r
        registry: docker.opensafely.org
        username: docker
        password: ${{ secrets.OPENSAFELY_DOCKER_PASSWORD }}
        buildargs:
